development:
  dialect: postgres
  datasource: host=localhost port=5432 user=postgres password=1234 dbname=postgres sslmode=disable
  dir: migrations
  table: migrations

#production:
#  dialect: postgres
#  datasource: dbname=myapp sslmode=disable
#  dir: migrations/postgres
#  table: migrations